services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb
    volumes:
      - /app/db/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8080

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /app/minio/data:/data
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=PASSWORD
    restart: always
    command: server --console-address ":9001" /data      

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
      - jupyter

  jupyter:
    build: ./app/jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./app/jupyter/data:/home/jovyan/work
    depends_on:
      - minio
    
  backend:
    build: ./app/backend
    ports:
      - 8000:80
    depends_on:
      - database
      - minio

